# Generated by Django 2.2 on 2019-05-03 16:55

from django.db import migrations

def create_tipo_empaque(apps, schema_monitor):
    '''
    Create tipo_empaque for empaques
    '''

    Tipo_empaque = apps.get_model('empaques_app', 'Tipo_empaque')

    Tipo_empaque.objects.create(nombre='cilindro')
    Tipo_empaque.objects.create(nombre='pallet')


def create_clase(apps, schema_monitor):
    '''
    Create class for empaque
    '''

    Clase = apps.get_model('empaques_app', 'Clase')

    Clase.objects.create(nombre='C1')
    Clase.objects.create(nombre='C2')
    Clase.objects.create(nombre='CI')


def create_modelo(apps, schema_monitor):
    '''
    Create modelo of empaque
    '''
    Modelo = apps.get_model('empaques_app', 'Modelo')

    Modelo.objects.create(nombre='AMONIACO GAS 64 KG')
    Modelo.objects.create(nombre='AMONIACO GAS 66 KG')


def create_estado(apps, schema_monitor):
    '''
    Create estado of empaque
    '''
    Estado = apps.get_model('empaques_app', 'Estado_empaque')

    Estado.objects.create(nombre='Bueno')
    Estado.objects.create(nombre='Dañado')
    Estado.objects.create(nombre='Reparando')


def create_ubicacion(apps, schema_monitor):
    '''
    Create ubications
    '''
    Ciudad = apps.get_model('empaques_app', 'Ciudad')
    Bodega = apps.get_model('empaques_app', 'Bodega')
    Estado_disp = apps.get_model('empaques_app', 'Estado_disponibilidad')
    Ubicacion = apps.get_model('empaques_app', 'Ubicacion')

    gye = Ciudad.objects.create(nombre='Guayaquil')
    Ciudad.objects.create(nombre='Quito')
    Ciudad.objects.create(nombre='Ambato')

    bodenorte = Bodega.objects.create(nombre='BODENORTE', ciudad=gye)
    agronorte = Bodega.objects.create(nombre='AGRONORTE', ciudad=gye)

    lleno = Estado_disp.objects.create(nombre='Lleno')
    vacio = Estado_disp.objects.create(nombre='Vacio')
    en_uso = Estado_disp.objects.create(nombre='En Uso')

    Ubicacion.objects.create(bodega=bodenorte, estado_disp=lleno)
    Ubicacion.objects.create(bodega=bodenorte, estado_disp=vacio)
    Ubicacion.objects.create(bodega=bodenorte, estado_disp=en_uso)

    Ubicacion.objects.create(bodega=agronorte, estado_disp=en_uso)
    Ubicacion.objects.create(bodega=agronorte, estado_disp=vacio)
    Ubicacion.objects.create(bodega=agronorte, estado_disp=lleno)


def create_custodio(apps, schema_monitor):
    '''
    Create predeterminated custodio
    '''

    Empresa = apps.get_model('empaques_app', 'Empresa')
    Repre_emp = apps.get_model('empaques_app', 'Representante_empresa')
    Custodio = apps.get_model('empaques_app', 'Custodio')

    empresa = Empresa.objects.create(
        codigo='001',
        nombre='Brenntag',
        RUC='0990005087001'
    )

    repre = Repre_emp.objects.create(
        cedula='0000000000',
        nombre='..Brenntag',
        empresa=empresa
    )

    Custodio.objects.create(representante=repre, vendedor=repre)


class Migration(migrations.Migration):

    dependencies = [
        ('empaques_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_tipo_empaque),
        migrations.RunPython(create_clase),
        migrations.RunPython(create_modelo),
        migrations.RunPython(create_estado),
        migrations.RunPython(create_ubicacion),
        migrations.RunPython(create_custodio),
    ]
