# Generated by Django 2.2 on 2019-07-30 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques_app', '0002_auto_20190503_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenempaquesdetail',
            name='fecha_retorno',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ordenempaquesdetail',
            name='observacion_retorno',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='RUC',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[0-9]{13}')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
