# Generated by Django 2.2 on 2019-07-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques_app', '0003_auto_20190730_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenempaquesdetail',
            name='fecha_despacho',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
