# Generated by Django 2.2 on 2019-07-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques_app', '0004_ordenempaquesdetail_fecha_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_despacho',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
