# Generated by Django 2.2 on 2019-07-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques_app', '0005_orden_fecha_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_retorno',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
