# Generated by Django 2.2 on 2019-05-03 16:55

from django.db import migrations

def create_estado(apps, schema_monitor):
    '''
    Create estado of empaque
    '''
    Estado = apps.get_model('empaques_app', 'Estado_empaque')

    Estado.objects.create(nombre='Bueno')
    Estado.objects.create(nombre='Dañado')
    Estado.objects.create(nombre='Reparando')


def create_ubicacion(apps, schema_monitor):
    '''
    Create ubications
    '''
    Ciudad = apps.get_model('empaques_app', 'Ciudad')
    Bodega = apps.get_model('empaques_app', 'Bodega')
    Estado_disp = apps.get_model('empaques_app', 'Estado_disponibilidad')
    Ubicacion = apps.get_model('empaques_app', 'Ubicacion')

    gye = Ciudad.objects.create(nombre='Guayaquil')
    qto = Ciudad.objects.create(nombre='Quito')
    amb = Ciudad.objects.create(nombre='Ambato')

    bodenorte = Bodega.objects.create(nombre='BODENORTE', ciudad=gye)
    agronorte = Bodega.objects.create(nombre='AGRONORTE', ciudad=gye)
    bquito = Bodega.objects.create(nombre='B. QUITO', ciudad=qto)
    bambato = Bodega.objects.create(nombre='B. AMBATO', ciudad=amb)

    lleno = Estado_disp.objects.create(nombre='Lleno')
    vacio = Estado_disp.objects.create(nombre='Vacio')
    en_uso = Estado_disp.objects.create(nombre='En Uso')
    fuera_servicio = Estado_disp.objects.create(nombre='Fuera de servicio')

    Ubicacion.objects.create(bodega=bodenorte, estado_disp=lleno)
    Ubicacion.objects.create(bodega=bodenorte, estado_disp=vacio)
    Ubicacion.objects.create(bodega=bodenorte, estado_disp=en_uso)
    Ubicacion.objects.create(bodega=bodenorte, estado_disp=fuera_servicio)

    Ubicacion.objects.create(bodega=agronorte, estado_disp=en_uso)
    Ubicacion.objects.create(bodega=agronorte, estado_disp=vacio)
    Ubicacion.objects.create(bodega=agronorte, estado_disp=fuera_servicio)
    Ubicacion.objects.create(bodega=agronorte, estado_disp=lleno)

    Ubicacion.objects.create(bodega=bquito, estado_disp=en_uso)
    Ubicacion.objects.create(bodega=bquito, estado_disp=vacio)
    Ubicacion.objects.create(bodega=bquito, estado_disp=fuera_servicio)
    Ubicacion.objects.create(bodega=bquito, estado_disp=lleno)

    Ubicacion.objects.create(bodega=bambato, estado_disp=en_uso)
    Ubicacion.objects.create(bodega=bambato, estado_disp=vacio)
    Ubicacion.objects.create(bodega=bambato, estado_disp=fuera_servicio)
    Ubicacion.objects.create(bodega=bambato, estado_disp=lleno)


def create_cilindros(apps, schema_monitor):
    '''
    Create predeterminated cilindros
    '''
    Ubicacion = apps.get_model('empaques_app', 'Ubicacion')
    Empresa = apps.get_model('empaques_app', 'Empresa')
    Representante = apps.get_model('empaques_app', 'Representante_empresa')
    Custodio = apps.get_model('empaques_app', 'Custodio')
    Tipo_empaque = apps.get_model('empaques_app', 'Tipo_empaque')
    Clase = apps.get_model('empaques_app', 'Clase')
    Modelo = apps.get_model('empaques_app', 'Modelo')
    Estado = apps.get_model('empaques_app', 'Estado_empaque')
    Empaque = apps.get_model('empaques_app', 'Empaque')

    bueno = Estado.objects.create(nombre='Bueno')
    dan = Estado.objects.create(nombre='Dañado')
    rep = Estado.objects.create(nombre='Reparando')

    modelo64 = Modelo.objects.create(nombre='AMONIACO GAS 64 KG')
    modelo66 = Modelo.objects.create(nombre='AMONIACO GAS 66 KG')

    c1 = Clase.objects.create(nombre='C1')
    c2 = Clase.objects.create(nombre='C2')
    ci = Clase.objects.create(nombre='CI')


    cilindro = Tipo_empaque.objects.create(nombre='cilindro')
    Tipo_empaque.objects.create(nombre='pallet')

    empresa = Empresa.objects.create(
        codigo='001',
        nombre='BRENNTAG',
        RUC='0990005087001'
    )

    repre = Representante.objects.create(
        cedula='0000000000',
        nombre='..Brenntag',
        empresa=empresa
    )

    custodio_bren = Custodio.objects.create(representante=repre, vendedor=repre)

    bodenorte_lleno = Ubicacion.objects.get(bodega__nombre='BODENORTE', estado_disp__nombre='Lleno')
    bodenorte_fds = Ubicacion.objects.get(bodega__nombre='BODENORTE', estado_disp__nombre='Fuera de servicio')
    bodenorte_vacio = Ubicacion.objects.get(bodega__nombre='BODENORTE', estado_disp__nombre='Vacio')


def create_custodio(apps, schema_monitor):
    '''
    Create predeterminated custodio
    '''

    Empresa = apps.get_model('empaques_app', 'Empresa')
    Representante = apps.get_model('empaques_app', 'Representante_empresa')
    Custodio = apps.get_model('empaques_app', 'Custodio')
    Correo = apps.get_model('empaques_app', 'Correo')


    empresa = Empresa.objects.get(nombre='BRENNTAG', codigo='001')
    # Crear Vendedor

    IR = Representante.objects.create(
        nombre="Ivan Rodriguez",
        empresa=empresa
    )

    WI = Representante.objects.create(
        nombre="Winston Intriago",
        empresa=empresa
    )

    VC = Representante.objects.create(
        nombre="Veronica Costales",
        empresa=empresa
    )

    RM = Representante.objects.create(
        nombre="Raul Moreno",
        empresa=empresa
    )

    MM = Representante.objects.create(
        nombre="Mariela Montenegro",
        empresa=empresa
    )

    IJ = Representante.objects.create(
        nombre="Irving Jimenez",
        empresa=empresa
    )

    DD = Representante.objects.create(
        nombre="Diego Delgado",
        empresa=empresa
    )

    DP = Representante.objects.create(
        nombre="Diana Pazmiño",
        empresa=empresa
    )

    SM = Representante.objects.create(
        nombre="Santiago Muñoz",
        empresa=empresa
    )

    # Creando empresas

    emp = Empresa.objects.create(
        nombre="EXOHIELO S.A.",
        codigo="EX2030",
        RUC="0791787084001"
    )

    correo = Correo.objects.create(correo="gerencia@exohielo.com")

    repre = Representante.objects.create(
        nombre="Marcos Alfredo Robalino",
        nombre_carta="Marcos Alfredo Robalino",
        empresa=emp
    )

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=IR)

    emp = Empresa.objects.create(
        nombre="LEONES ZEVALLOS ANGEL JOSE",
        codigo="LE2017",
        RUC="1202502702001"
    )

    repre = Representante.objects.create(
        nombre="Leones Zevallos Angel Jose",
        nombre_carta="Leones Zevallos Angel Jose",
        empresa=emp
    )

    correo = Correo.objects.create(correo="karyosa@yahoo.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=WI)


    emp = Empresa.objects.create(
        nombre="OCEAN ICE",
        codigo="OC2156",
        RUC="099248574001"
    )

    repre = Representante.objects.create(
        nombre="Guido Arias",
        nombre_carta="Guido Arias",
        empresa=emp
    )

    correo = Correo.objects.create(correo="oceanice@hotmail.es")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=WI)


    emp = Empresa.objects.create(
        nombre="UNILEVER ANDINA ECUADOR S.A.",
        codigo="UN2010/HE2002",
        RUC="1791321596001"
    )

    repre = Representante.objects.create(
        nombre="Marco Anchala",
        nombre_carta="Francisco Solano Minga",
        empresa=emp
    )

    correo = Correo.objects.create(correo="oceanice@hotmail.es")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=VC)


    emp = Empresa.objects.create(
        nombre="CERVECERIA NACIONAL CN S.A.",
        codigo="CE2015",
        RUC="0990023549001"
    )

    repre = Representante.objects.create(
        nombre="Maria gaibor",
        nombre_carta="Maria Gaibor",
        empresa=emp
    )

    correo = Correo.objects.create(correo="Maria.Gaibor@ec.ab-inbev.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=RM)


    emp = Empresa.objects.create(
        nombre="COMPANIA DE ELABORADOS DE CAFE EL CAFE C.A.",
        codigo="GE2003",
        RUC="1390059694001"
    )

    repre = Representante.objects.create(
        nombre="Gilda Rivadeneira",
        nombre_carta="Gilda Rivadeneira",
        empresa=emp
    )

    correo = Correo.objects.create(correo="grivadeneira@cafeelcafe.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)


    emp = Empresa.objects.create(
        nombre="DIMOLFIN S.A.",
        codigo="DI2088",
        RUC="0992305401001"
    )

    repre = Representante.objects.create(
        nombre="Maria Jose Mérchan",
        nombre_carta="Maria Jose Mérchan",
        empresa=emp
    )

    correo = Correo.objects.create(correo="mjmerchan@feed-pro.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)


    emp = Empresa.objects.create(
        nombre="EMPACADORA PUNTARENA S.A.",
        codigo="EM2199",
        RUC="0991170324001"
    )

    repre = Representante.objects.create(
        nombre="Ericka Usey",
        nombre_carta="Ericka Usey",
        empresa=emp
    )

    correo = Correo.objects.create(correo="compras2.langosmar@gmail.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=IJ)

    emp = Empresa.objects.create(
        nombre="EMPRESA PESQUERA POLAR S.A.",
        codigo="EM2077",
        RUC="0990182086001"
    )

    repre = Representante.objects.create(
        nombre="Juan Carlos Bravo",
        nombre_carta="Juan Carlos Bravo",
        empresa=emp
    )

    correo = Correo.objects.create(correo="jbravo@pesquerapolar.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)


    emp = Empresa.objects.create(
        nombre="ESTAR C.A.",
        codigo="EM2018",
        RUC="0990533652001"
    )

    repre = Representante.objects.create(
        nombre="Rosa Jaramillo",
        nombre_carta="Rosa Jaramillo",
        empresa=emp
    )

    correo = Correo.objects.create(correo="comprasestarca@gquirola.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)


    emp = Empresa.objects.create(
        nombre="ESTRID S.A.",
        codigo="ES2099",
        RUC="0991289283001"
    )

    repre = Representante.objects.create(
        nombre="Carlos Acuria",
        nombre_carta="Carlos Acuria",
        empresa=emp
    )

    correo = Correo.objects.create(correo="cacuria@il-gelato.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)


    emp = Empresa.objects.create(
        nombre="EXPORTADORA TOTAL SEAFOOD TOTALSEAFOOD S.A",
        codigo="SE2095",
        RUC="0992911956001"
    )

    repre = Representante.objects.create(
        nombre="Andres Orrantia",
        nombre_carta="Andres Orrantia",
        empresa=emp
    )

    correo = Correo.objects.create(correo="aorrantia@limasol.net")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=IJ)


    emp = Empresa.objects.create(
        nombre="INDUSTRIA LECHERA FLORALP",
        codigo="IN3017",
        RUC="1090067563001"
    )

    repre = Representante.objects.create(
        nombre="Victoria Caicedo",
        nombre_carta="Victoria Caicedo",
        empresa=emp
    )

    correo = Correo.objects.create(correo="victoria.caicedo@floralp-sa.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)


    emp = Empresa.objects.create(
        nombre="INDUSTRIAL PESQUERA SANTA PRISCILA S.A.",
        codigo="IN2105",
        RUC="0991257721001"
    )

    repre = Representante.objects.create(
        nombre="Neiva Morales",
        nombre_carta="Neiva Morales",
        empresa=emp
    )

    correo = Correo.objects.create(correo="neiva.morales@ipsp-profremar.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=DD)

    repre = Representante.objects.create(
        nombre="Kathy Quimi",
        nombre_carta="Kathy Quimi",
        empresa=emp
    )

    correo = Correo.objects.create(correo="nilda.noboa@ipsp-profremar.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=DD)

    repre = Representante.objects.create(
        nombre="John Horna",
        nombre_carta="John Horna",
        empresa=emp
    )

    correo = Correo.objects.create(correo="jhorna@santa-priscila.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=DD)


    emp = Empresa.objects.create(
        nombre="INDUSTRIAL SURINDU S.A.",
        codigo="IN2082",
        RUC="0991366849001"
    )

    repre = Representante.objects.create(
        nombre="Giuliana Javier",
        nombre_carta="Giuliana Javier",
        empresa=emp
    )

    correo = Correo.objects.create(correo="Giuliana.Javier@ec.nestle.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=VC)

    emp = Empresa.objects.create(
        nombre="JADE S.A.JADESA",
        codigo="JA2011",
        RUC="0992303166001"
    )

    repre = Representante.objects.create(
        nombre="Jose Murillo",
        nombre_carta="Jose Murillo",
        empresa=emp
    )

    correo = Correo.objects.create(correo="jmurillo@jade.com.e")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)

    emp = Empresa.objects.create(
        nombre="OPERADORA Y PROCESADORA DE PRODUCTOS MARINOS OMARSA S.A.",
        codigo="OM2001",
        RUC="0990608504001"
    )

    repre = Representante.objects.create(
        nombre="Gines Cecilia",
        nombre_carta="Gines Cecilia",
        empresa=emp
    )

    correo = Correo.objects.create(correo="cecilia@omarsa.com.ec")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=DD)

    emp = Empresa.objects.create(
        nombre="PESQUERA CENTROMAR S.A.",
        codigo="PE2016",
        RUC="0990867968001"
    )

    repre = Representante.objects.create(
        nombre="Antonio Dominguez",
        nombre_carta="Antonio Dominguez",
        empresa=emp
    )

    correo = Correo.objects.create(correo="mdominguez@centromar.ec")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)

    emp = Empresa.objects.create(
        nombre="PROEXPO, PROCESADORA Y EXPORTADORA DE MARISCOS S.A.",
        codigo="PR2087",
        RUC="0992597895001"
    )

    repre = Representante.objects.create(
        nombre="Katherine Bastidas",
        nombre_carta="Luisa Rosales",
        empresa=emp
    )

    correo = Correo.objects.create(correo="kbastidas@proexpo.com.ec")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)

    emp = Empresa.objects.create(
        nombre="REYLACTEOS S.A.",
        codigo="RE2048",
        RUC="0993062588001"
    )

    repre = Representante.objects.create(
        nombre="Luis Zurita",
        nombre_carta="Luis Zurita",
        empresa=emp
    )

    correo = Correo.objects.create(correo="luzurita@favoritafc.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=RM)

    emp = Empresa.objects.create(
        nombre="SEAFMAN C.A.",
        codigo="SE8001",
        RUC="1790034305001"
    )

    repre = Representante.objects.create(
        nombre="Abraham Palma",
        nombre_carta="Abraham Palma",
        empresa=emp
    )

    correo = Correo.objects.create(correo="apalma@seafman.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)

    emp = Empresa.objects.create(
        nombre="SOCIEDAD NACIONAL DE GALAPAGOS C.A.",
        codigo="SO2000",
        RUC="0990033110001"
    )

    repre = Representante.objects.create(
        nombre="Jessica Suarez",
        nombre_carta="Jessica Suarez",
        empresa=emp
    )

    correo = Correo.objects.create(correo="jsuarez@songa.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=DD)

    emp = Empresa.objects.create(
        nombre="TROPICAL PACKING ECUADOR S.A. TROPACK",
        codigo="TR2090",
        RUC="0992708581001"
    )

    repre = Representante.objects.create(
        nombre="Adriana Beltran",
        nombre_carta="Adriana Beltran",
        empresa=emp
    )

    correo = Correo.objects.create(correo="abeltran@tropack.com.ec")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)

    emp = Empresa.objects.create(
        nombre="TROPIFRUTAS S.A.",
        codigo="TR2003",
        RUC="0990914559001"
    )

    repre = Representante.objects.create(
        nombre="Paola Avecillas",
        nombre_carta="Paola Avecillas",
        empresa=emp
    )

    correo = Correo.objects.create(correo="pavecillas@tropifrutas.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)

    emp = Empresa.objects.create(
        nombre="VINOS DOS HEMISFERIOS C.A.",
        codigo="VH2001",
        RUC="0992764570001"
    )

    repre = Representante.objects.create(
        nombre="Celeste Aguirre",
        nombre_carta="Celeste Aguirre",
        empresa=emp
    )

    correo = Correo.objects.create(correo="asisgerencia@doshemisferios.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)

    emp = Empresa.objects.create(
        nombre="WORLDWIDE INVESTMENTS AND REPRESENTATIONS WINREP S.A.",
        codigo="WO2020",
        RUC="0992728299001"
    )

    repre = Representante.objects.create(
        nombre="Rossana Bejarano",
        nombre_carta="Rossana Bejarano",
        empresa=emp
    )

    correo = Correo.objects.create(correo="rbejarano@winrep.net")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=MM)


    emp = Empresa.objects.create(
        nombre="OLYMPIC JUICE OLYJUICE CIA.LTDA.",
        codigo="OL3009",
        RUC="1792065585001"
    )

    repre = Representante.objects.create(
        nombre="Se. Fernando chicaiza",
        nombre_carta="Paulina Pucha  Fernanda Chicaiza",
        empresa=emp
    )

    correo = Correo.objects.create(correo="fchicaiza@orangine.com.ec")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=DP)

    emp = Empresa.objects.create(
        nombre="JABONERIA WILSON S.A.",
        codigo="JA3000",
        RUC="1790160793001"
    )

    repre = Representante.objects.create(
        nombre="Katherine Cañar",
        nombre_carta="Katherine Cañar",
        empresa=emp
    )

    correo = Correo.objects.create(correo="kcanar@jaboneriawilson.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=IR)

    emp = Empresa.objects.create(
        nombre="ECOFROZ S.A.",
        codigo="EC3025",
        RUC="1791295706001"
    )

    repre = Representante.objects.create(
        nombre="Sr. Bernardo Guarderas",
        nombre_carta="Sr. Bernardo Guarderas",
        empresa=emp
    )

    correo = Correo.objects.create(correo="bguarderas@ecofroz.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=SM)

    emp = Empresa.objects.create(
        nombre="BEBIDAS ARCA CONTINENTAL ARCADOR S.A.",
        codigo="AR2869",
        RUC="1792411149001"
    )

    repre = Representante.objects.create(
        nombre="Jessica Salinas",
        nombre_carta="Jessica Salinas",
        empresa=emp
    )

    correo = Correo.objects.create(correo="jessica.salinas@arcacontal.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=SM)

    emp = Empresa.objects.create(
        nombre="ABELLITO S.A.",
        codigo="AB4005",
        RUC="0992144009001"
    )

    repre = Representante.objects.create(
        nombre="Veronica Tapia",
        nombre_carta="Veronica Tapia",
        empresa=emp
    )

    correo = Correo.objects.create(correo="e.verotapia@gmail.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=SM)

    emp = Empresa.objects.create(
        nombre="PRODUCTORA DE GELATINA ECUATORIANA S.A. PRODEGEL",
        codigo="PR4010",
        RUC="1792183154001"
    )

    repre = Representante.objects.create(
        nombre="Soledad Mejia",
        nombre_carta="Soledad Mejia",
        empresa=emp
    )

    correo = Correo.objects.create(correo="soledad.mejia@gelcointernational.com")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=SM)

    emp = Empresa.objects.create(
        nombre="LECHE GLORIA - ECUADOR S.A.",
        codigo="le3006",
        RUC="1790663973001"
    )

    repre = Representante.objects.create(
        nombre="Gabriela Almeida",
        nombre_carta="Gabriela Almeida",
        empresa=emp
    )

    correo = Correo.objects.create(correo="malmeida@andina.com.ec")

    repre.correos.add(correo)

    Custodio.objects.create(representante=repre, vendedor=SM)


def create_tipo_orden(apps, schema_monitor):
    '''
    Create predeterminated tipo de orden
    '''
    TipoOrden = apps.get_model('empaques_app', 'Tipo_orden')

    TipoOrden.objects.create(
        nombre="Transaccion",
        descripcion="Cambio de custodio original (Brenntag), a custodio externo"
    )

    TipoOrden.objects.create(
        nombre="Transferencia",
        descripcion="Cambio de ubicacion, custodio (Brenntag)"
    )

    TipoOrden.objects.create(
        nombre="Venta",
        descripcion="Cambio de custodio, cambio de estado (vendido)"
    )



class Migration(migrations.Migration):

    dependencies = [
        ('empaques_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_ubicacion),
        migrations.RunPython(create_cilindros),
        migrations.RunPython(create_custodio),
        migrations.RunPython(create_tipo_orden),
    ]
